apache/commons-codec

src/main/java/org/apache/commons/codec/Resources.java, src/main/java/org/apache/commons/codec/digest/B64.java, src/main/java/org/apache/commons/codec/digest/Crypt.java, src/main/java/org/apache/commons/codec/digest/DigestUtils.java, src/main/java/org/apache/commons/codec/digest/Md5Crypt.java, src/main/java/org/apache/commons/codec/digest/Sha2Crypt.java, src/main/java/org/apache/commons/codec/language/ColognePhonetic.java, src/main/java/org/apache/commons/codec/language/DaitchMokotoffSoundex.java, src/main/java/org/apache/commons/codec/net/PercentCodec.java, src/main/java/org/apache/commons/codec/net/QuotedPrintableCodec.java, src/test/java/org/apache/commons/codec/StringEncoderAbstractTest.java, src/test/java/org/apache/commons/codec/StringEncoderComparatorTest.java, src/test/java/org/apache/commons/codec/net/BCodecTest.java, src/test/java/org/apache/commons/codec/net/QCodecTest.java, src/test/java/org/apache/commons/codec/net/QuotedPrintableCodecTest.java, src/test/java/org/apache/commons/codec/net/URLCodecTest.java
Fixes one generics warning, deprecation warnings from tests, and other issues from Checkstyle, and FindBugs.
Will merge if Travis is happy and if there is no objections in the next days.
Cheers
Bruno
=> Minor improvements

src/main/java/org/apache/commons/codec/digest/Md5Crypt.java
Should fix travis build. Removes duplicated `@param`, and adds `@return` value.
=> Fix javadoc (and Travis build)

src/changes/changes.xml, src/main/java/org/apache/commons/codec/binary/Base32.java, src/main/java/org/apache/commons/codec/binary/Base64.java, src/main/java/org/apache/commons/codec/net/BCodec.java, src/test/java/org/apache/commons/codec/binary/Base32Test.java, src/test/java/org/apache/commons/codec/binary/Base64Test.java, src/test/java/org/apache/commons/codec/binary/Base64TestData.java, src/test/java/org/apache/commons/codec/net/BCodecTest.java
=> CODEC-134: Update commons-codec to reject decoding any impossible string encoding for Base32 and Base64.

src/changes/changes.xml, src/main/java/org/apache/commons/codec/digest/MurmurHash2.java, src/main/java/org/apache/commons/codec/digest/MurmurHash3.java, src/test/java/org/apache/commons/codec/digest/MurmurHash2Test.java, src/test/java/org/apache/commons/codec/digest/MurmurHash3Test.java
All MurmurHash implementations are public domain.
Credit was given in Javadoc where both implementations came from.
=> CODEC-236: MurmurHash2 and MurmurHash3 implementations.

src/changes/changes.xml, src/main/java/org/apache/commons/codec/binary/Base32.java, src/main/java/org/apache/commons/codec/binary/Base64.java, src/test/java/org/apache/commons/codec/binary/Base32Test.java, src/test/java/org/apache/commons/codec/binary/Base64Test.java, src/test/java/org/apache/commons/codec/net/BCodecTest.java
Fixed the Base32/64 mask check to ensure it checks all the bits to be discarded are zero.
Added tests that enumerate all possible trailing characters. Only those with zero for the discarded bits should be decoded.
Also fixed the BCodecTest data to use the RFC 1522 "encoded-word" header.
=> [CODEC-270] Base32/64: Fix masked check of the final bits to discard.

src/changes/changes.xml, src/main/java/org/apache/commons/codec/binary/BaseNCodec.java, src/test/java/org/apache/commons/codec/binary/Base64Test.java, src/test/java/org/apache/commons/codec/binary/BaseNCodecTest.java
Re: [CODEC-265] Add a test to encode a 1 Gigabyte byte[].
Added overflow conscious code for buffer expansion during encoding and decoding. This is based on java.util.ArrayList but modified to use a local copy of JDK 1.8 Integer.compareUnsigned(int, int) to compare the new buffer capacity to the required capacity.
Unlike the java.util.ArrayList if the minCapacity exceeds the head room for the maximum array size, the capacity returned is the required minCapacity and not Integer.MAX_VALUE. This allows the test `testEnsureBufferSizeExpandsToBeyondMaxBufferSize` to pass on my machine using:
```
java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
``` 
If I return …
=> [CODEC-265] BaseNCodec to expand buffer using overflow conscious code.

src/changes/changes.xml, src/main/java/org/apache/commons/codec/binary/Hex.java, src/test/java/org/apache/commons/codec/binary/HexTest.java, src/test/java/org/apache/commons/codec/binary/StringUtilsTest.java
The use of ByteBuffer.array() for any array-backed buffers means that the Hex class can produce incorrect results if the backing array is not entirely filled with the data to encode/decode.
This fixes the implementation by only using the backing array if the length is equal to the reported capacity. Otherwise the methods using ByteBuffer default to copying the remaining bytes into a copy array.
The code has been documented as using all remaining bytes in the input ByteBuffer. The methods now handle input array backed ByteBuffers and directly allocated ByteBuffers equally.
Tests have been added using limits on the buffer to encode/decode a sub-section of the bytes.
The tests have been updated so all tests are run with a direct allocated ByteBuffer in AllocateDirectHexTest.
=> [codec-259] Hex: consume all ByteBuffer.remaining() bytes

src/main/java/org/apache/commons/codec/digest/MurmurHash3.java
=> Added javadoc messages concerning hash64 seed and sign extension.

src/changes/changes.xml, src/main/java/org/apache/commons/codec/binary/Base32.java, src/main/java/org/apache/commons/codec/binary/Base64.java, src/main/java/org/apache/commons/codec/binary/BaseNCodec.java, src/main/java/org/apache/commons/codec/net/BCodec.java, src/test/java/org/apache/commons/codec/binary/Base32Test.java, src/test/java/org/apache/commons/codec/binary/Base64Test.java, src/test/java/org/apache/commons/codec/net/BCodecTest.java
The default is lenient encoding. Any trailing bits that cannot be
interpreted as part of the encoding are discarded. Combinations of
trailing characters that cannot be created by a valid encoding are
partially interpreted.
If set to strict encoding the codec will raise an exception when
trailing bits are present that are not part of a valid encoding.
Added tests to show that in lenient mode re-encoding will create a
different byte array.
In strict mode the re-encoding should create the same byte array as the
original (with appropriate pad characters on the input).
The PR does not current address behaviour of BCodec class that uses Base64. The test that validates input that requires strict mode have been disabled to allow travis to pass.
=> [CODEC-280] Added strict decoding property to BaseNCodec.

src/main/java/org/apache/commons/codec/digest/MurmurHash3.java
Noticed a minor javadocs issue - some classes had "from from" instead of "from"
Quick PR to fix this. Does not impact code so should not need any extra testing.
(I noticed I messed up adding "(doc)" to the actual commit - I can submit a revised PR or force push an updated commit message if needed - it also seems like I shouldn't need to sign a CLA due to how minor this is, but let me know if there's anything I'm missing :) )
=> (doc) Remove duplicate "from"s in javadoc comments

src/main/java/org/apache/commons/codec/binary/BinaryCodec.java, src/main/java/org/apache/commons/codec/binary/Hex.java, src/main/java/org/apache/commons/codec/cli/Digest.java, src/main/java/org/apache/commons/codec/digest/Md5Crypt.java, src/main/java/org/apache/commons/codec/digest/MurmurHash3.java, src/main/java/org/apache/commons/codec/digest/UnixCrypt.java, src/main/java/org/apache/commons/codec/language/Metaphone.java, src/main/java/org/apache/commons/codec/language/bm/Rule.java, src/main/java/org/apache/commons/codec/net/QuotedPrintableCodec.java, src/main/java/org/apache/commons/codec/net/RFC1522Codec.java, src/test/java/org/apache/commons/codec/binary/Base16Test.java, src/test/java/org/apache/commons/codec/binary/Base32Test.java, src/test/java/org/apache/commons/codec/binary/Base64Test.java, src/test/java/org/apache/commons/codec/binary/HexTest.java, src/test/java/org/apache/commons/codec/cli/DigestTest.java, src/test/java/org/apache/commons/codec/language/bm/PhoneticEngineRegressionTest.java
https://issues.apache.org/jira/browse/CODEC-295
Minor improvement 
- extra computations by getting the string size only once.
- remove unused imports
- add final String
- add final method and var
- FIx javadoc
=> [CODEC-295] - Minor improvements

src/main/java/org/apache/commons/codec/language/MatchRatingApproachEncoder.java
These constants are much harder to read than just the regular numbers, and are often only used once as well, so removing them makes the code more readable - to me at least.
=> Remove hardcoded constants to improve readability

pom.xml
Handles https://issues.apache.org/jira/browse/CODEC-285
Also based upon https://issues.apache.org/jira/browse/CODEC-284 branch so pr https://github.com/apache/commons-codec/pull/38
=> CODEC-285 upgrade to JUnit v5.6.0

pom.xml, src/test/java/org/apache/commons/codec/StringEncoderAbstractTest.java
Follow up for PR https://github.com/apache/commons-codec/pull/39
From experience people write tests that don't check exceptions correctly, either they are not thrown, or a different than expected line throws that exception, or it's the wrong exception, or wrong message.
This test doesn't ever throw the exception listed, so why is it catching and ignoring if thrown???
=> CODEC-285 Better StringEncoderAbstractTest testEncodeNull

src/test/java/org/apache/commons/codec/binary/HexTest.java
Looking at @Test(expected) and test method body, the last line usually throws the expected but test actually fails earlier.
=> CODEC-285 HexTest

.github/workflows/maven.yml
GitHub asks developers to define workflow permissions, see https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/ and https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token for securing GitHub workflows against supply-chain attacks.
The Open Source Security Foundation (OpenSSF) [Scorecards](https://github.com/ossf/scorecard) also treats not setting token permissions as a high-risk issue. 
This PR adds minimum token permissions for the GITHUB_TOKEN using https://github.com/step-security/secure-workflows. 
This project is part of the top 100 critical projects as per OpenSSF (https://github.com/ossf/wg-securing-critical-projects), so fixing the token permissions to improve …
=> ci: Add GitHub token permissions for workflows

src/main/java/org/apache/commons/codec/binary/Base64.java
In `Base64.java`, change leftover mention of `BASE32` to `BASE64`.
=> correct error in Base64 javadoc

src/main/java/org/apache/commons/codec/digest/Crypt.java, src/main/java/org/apache/commons/codec/digest/Md5Crypt.java, src/main/java/org/apache/commons/codec/digest/Sha2Crypt.java, src/main/java/org/apache/commons/codec/digest/UnixCrypt.java, src/site/xdoc/userguide.xml
This PR:
* Documents that SecureRandom is used in Crypt, Md5Crypt and Sha2Crypt classes by changing Javadocs in these classes (by calling B64.randomSalt)
* Changes salt generation in UnixCrypt to use SecureRandom to match the other classes
* Update the userguide to list all functions from the digest package
* Changes the hyperlinks in the user guide from HTTP to HTTPS
See https://issues.apache.org/jira/browse/CODEC-310
=> CODEC-310 - Documentation update for the org.apache.commons.codec.digest.* package

src/main/java/org/apache/commons/codec/language/bm/PhoneticEngine.java, src/test/java/org/apache/commons/codec/language/bm/PhoneticEngineTest.java
This fixes possible StringIndexOutOfBoundsException and ArrayIndexOutOfBoundsException in [src/main/java/org/apache/commons/codec/language/bm/PhoneticEngine.java](https://github.com/apache/commons-codec/blob/master/src/main/java/org/apache/commons/codec/language/bm/PhoneticEngine.java) thrown by `PhoneticEngine.encode()` when the provided string only contains one of the name prefix of the chosen NameType or only contain single quotation character.
This PR fixes the parameter for the split method and adds a conditional check to ensure only strings and arrays are not empty before processing.
We found this bug using fuzzing by way of OSS-Fuzz. It is reported at https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64376 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64395.
=> CODEC-315: Fix possible IndexOutOfBoundException thrown by PhoneticEngine.encode method

src/main/java/org/apache/commons/codec/net/QuotedPrintableCodec.java, src/test/java/org/apache/commons/codec/net/QuotedPrintableCodecTest.java
This fixes a possible ArrayIndexOutOfBoundException in [src/main/java/org/apache/commons/codec/language/QuotedPrintableCodec.java](https://github.com/apache/commons-codec/blob/master/src/main/java/org/apache/commons/codec/language/QuotedPrintableCodec.java) thrown by `QuotedPrintableCodec.encodeQuotedPrintable()` method when the input byte array has less than 3 elements.
This PR adds a conditional check to ensure the index is never negative. It will simply return null if the byte array is too short (with a length less than 3) if strict value is true.
We found this bug using fuzzing by way of OSS-Fuzz. It is reported at https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64358.
=> CODEC-313: Fix possible ArrayIndexOutOfBoundsException thrown by QuotedPrintableCodec.encodeQuotedPrintable() method

src/main/java/org/apache/commons/codec/language/MatchRatingApproachEncoder.java, src/test/java/org/apache/commons/codec/language/MatchRatingApproachEncoderTest.java
This fixes a possible StringIndexOutOfBoundException in [src/main/java/org/apache/commons/codec/language/MatchRatingApproachEncoder.java](https://github.com/apache/commons-codec/blob/master/src/main/java/org/apache/commons/codec/language/MatchRatingApproachEncoder.java) thrown by MatchRatingApproachEncoder.encode() method when the input string only contains punctuations or vowels.
This PR adds some conditional checking to ensure the string is not empty after each method call. If it is empty after any method call, it will simply return EMPTY and avoid continuing processing onto the next processing method.
We found this bug using fuzzing by way of OSS-Fuzz. It is reported at https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64359.
=> CODEC-312: Fix possible StringIndexOutOfBoundException thrown by MatchRatingApproachEncoder.encode() method

src/test/java/org/apache/commons/codec/binary/Base64Test.java
Near as I can tell this issue doesn't reproduce and can be closed. @garydgregory
=> [CODEC-263] test for user reported issue

src/main/java/org/apache/commons/codec/Resources.java, src/main/java/org/apache/commons/codec/language/DaitchMokotoffSoundex.java, src/main/java/org/apache/commons/codec/language/bm/Lang.java, src/main/java/org/apache/commons/codec/language/bm/Languages.java, src/main/java/org/apache/commons/codec/language/bm/Rule.java, src/test/java/org/apache/commons/codec/ResourcesTest.java
This plays nicer with Java's module system, as the class is able to load files from within the current module, whereas the classloader may not necessarily be able to.
Thanks for your contribution to [Apache Commons](https://commons.apache.org/)! Your help is appreciated!
Before you push a pull request, review this list:
=> Use Resource.class to load resources, rather than its classloader
